import Hero from '@/components/Hero'
import Head from 'next/head'
import Gallery from '@/components/Gallery'
import AboutUs from '@/components/AboutUs'
import Services from '@/components/Services'
import ContactUs from '@/components/ContactUs'

import { client } from '../lib/client'

export default function Home({ projects }) {
  return (
    <>
      <Head>
        <title>JAV Contractors App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='JAV Contractors' message='We focus on roofing, remodeling, and general contracting'/>
      <AboutUs />
      <Services />
      <Gallery projects={projects}/>
      <ContactUs />
    </>
  )
}

// The server fetches all content from Sanity.io
export const getServerSideProps = async () => {
  const query = '*[_type == "project"]';
  const projects = await client.fetch(query);
  return {
    props: { projects }
  }
}
