import Hero from '@/components/Hero'
import Head from 'next/head'
import Gallery from '@/components/Gallery'
import AboutUs from '@/components/AboutUs'
import Services from '@/components/Services'
import ContactUs from '@/components/ContactUs'

export default function Home() {
  return (
    <>
      <Head>
        <title>JAV Contractors App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='JAV Contractors' message='We focus on roofing, remodeling, and general contracting'/>
      <AboutUs />
      <Services />
      <Gallery />
      <ContactUs />
    </>
  )
}
